apiVersion: v1
kind: Secret
metadata:
  name: imagen-secrets
type: Opaque
stringData:
  postgres-password: postgres
  database-url: postgresql://postgres:postgres@postgres:5432/imagen
  minio-access-key: minioadmin
  minio-secret-key: minioadmin
